Add first adr documents
clipperz/password-manager pull request #150
Opened 2023-08-25 09:07 UTC by fsolaroli

2023-08-25 14:29 UTC, Gio-R requested changes

2023-08-25 14:29 UTC, Gio-R commented on doc/architecture/decisions/0002-technology-stack.md
> +The functional approach that the languages and frameworks chosen use will be a hard entry level as it differs from the "standard" way of writing software. On the other hand this approach allows the c
"chosen languages and frameworks" sounds better to me.

2023-08-25 14:29 UTC, Gio-R commented on doc/architecture/decisions/0003-sharing-widget-in-website.md
> +The interface will be very simple: the users will be presented with an area where they can insert their secret, a pre-generated PIN that can be changed with a button and a selection where they can ch
Given that, in the end, the secret is kept on the server more than the availability time, this sentence is misleading. "How much time the secret must be kept as available to users" may be a better choice.

2023-08-25 14:29 UTC, Gio-R commented on doc/architecture/decisions/0003-sharing-widget-in-website.md
> +Once these information are inserted, a button will be clickable to initiate the save of the encrypted secret on the server and create the link to share.
"to start saving the encrypted secret" sounds better to me.

2023-08-25 14:29 UTC, Gio-R commented on doc/architecture/decisions/0003-sharing-widget-in-website.md
> +The link will lead to the redeem page that will just contain an input to insert the pin and a button to initiate the retrieving of the secret. Once the pin is inserted and the button pressed, the sec
"text field" instead of "input" may be a better choice; "clicked" instead of "pressed" is more in line with the language used in previous paragraphs.

2023-08-25 14:29 UTC, Gio-R commented on doc/architecture/decisions/0003-sharing-widget-in-website.md
> +In the password generator widget (also inserted as a standalone page in the website) there will be also the possibility to share the secret generated. In this case the are to insert the secret will b
There is typo in "the are to insert"; "to prevent the user from changing it" sound better to me. Instead of "This maybe be" I think it should be "This may be", and instead of "could have already be" it should be "could have already been".

2023-08-25 14:29 UTC, Gio-R commented on doc/architecture/decisions/0003-sharing-widget-in-website.md
> +The random key will then be encrypted with the pin and used, alongside the id, to create the link to share.
Maybe "sharing link" could be a better choice than "link to share".

2023-08-25 14:29 UTC, Gio-R commented on doc/architecture/decisions/0003-sharing-widget-in-website.md
> +The response will also contain the version, that will allow to decern how to execute the operation mentioned above.
I think it should be "discern" instead of "decern".

2023-08-25 14:29 UTC, Gio-R commented on doc/architecture/decisions/0003-sharing-widget-in-website.md
> +The versioning will allow us to change how the secret is encoded and encrypted and change it easily, while keeping the redeem process working for secrets already saved in the backend.
I would change this sentence to something like "Versioning how the secret is encoded and encrypted will allow us to change how this is done in the future, while maintaining compatibility with older secrets created with a previous version of the process" for greater clarity: at a first read the meanings of two times "change" is used are not easily understood.

2023-08-25 14:29 UTC, Gio-R commented on doc/architecture/decisions/0003-sharing-widget-in-website.md
> +In case the secret is not found with the id contained in the request, a Not Found response (404) will be returned.
"In case no secret with the id contained in the request is found" sound a bit better to me.

2023-08-25 14:29 UTC, Gio-R commented on doc/architecture/decisions/0003-sharing-widget-in-website.md
> +The backend will not check periodically for the expiration dates of secrets as they take a very small amount of resources.
I would either specify that secrets occupy very little storage space or that keeping them uses a very small amount of resources. I wouldn't say that secrets "take resources".

2023-08-25 14:29 UTC, Gio-R commented on doc/architecture/decisions/0003-sharing-widget-in-website.md
> +https://www.clipperz.is/share
I would use a more complex phrase to describe the consequences, such as "The implementation of the feature described in this ADR is available at ...".

2023-08-25 15:37 UTC, fsolaroli commented on doc/architecture/decisions/0003-sharing-widget-in-website.md
> +The interface will be very simple: the users will be presented with an area where they can insert their secret, a pre-generated PIN that can be changed with a button and a selection where they can ch
What about:
```suggestion
The interface will be very simple: the users will be presented with an area where they can insert their secret, a pre-generated PIN that can be changed with a button and a selection where they can choose for how long the secret can be redeemable.
```?

2023-08-25 15:56 UTC, fsolaroli commented on doc/architecture/decisions/0003-sharing-widget-in-website.md
> +The random key will then be encrypted with the pin and used, alongside the id, to create the link to share.
"Share link", so it's the same term used in the button of the share form ("create share link")?

2023-08-25 16:08 UTC, fsolaroli commented on doc/architecture/decisions/0003-sharing-widget-in-website.md
> +The versioning will allow us to change how the secret is encoded and encrypted and change it easily, while keeping the redeem process working for secrets already saved in the backend.
Would this be better?

```suggestion
Versioning how the secret is encoded and encrypted will allow us to easily change how this is done, while maintaining compatibility with secrets created with older versions of the process.
```

2023-08-25 16:11 UTC, fsolaroli commented on doc/architecture/decisions/0003-sharing-widget-in-website.md
> +The backend will not check periodically for the expiration dates of secrets as they take a very small amount of resources.
```suggestion
The backend will not check periodically for the expiration dates of secrets as keeping them stored take a very small amount of resources.
```

2023-08-25 17:01 UTC, Gio-R commented on doc/architecture/decisions/0003-sharing-widget-in-website.md
> +The interface will be very simple: the users will be presented with an area where they can insert their secret, a pre-generated PIN that can be changed with a button and a selection where they can ch
Maybe without the "for"? But like this is ok too.

2023-08-25 17:01 UTC, Gio-R commented on doc/architecture/decisions/0003-sharing-widget-in-website.md
> +The random key will then be encrypted with the pin and used, alongside the id, to create the link to share.
Yes, that works.

2023-08-25 17:03 UTC, Gio-R commented on doc/architecture/decisions/0003-sharing-widget-in-website.md
> +The backend will not check periodically for the expiration dates of secrets as they take a very small amount of resources.
"takes" instead of "take", because "keeping" is singular, but other than that it works.

2023-08-25 17:08 UTC, Gio-R commented on doc/architecture/decisions/0003-sharing-widget-in-website.md
> +The versioning will allow us to change how the secret is encoded and encrypted and change it easily, while keeping the redeem process working for secrets already saved in the backend.
Yes, that works.

2023-08-27 15:10 UTC, gcsolaroli approved these changes

2023-08-27 15:11 UTC, gcsolaroli approved these changes

2023-08-27 15:13 UTC, gcsolaroli commented
This Pull Request ended up including too many unrelated changes.
Closing it up in order to submit a new one, cleaner one.

2023-08-27 15:13 UTC, closed without merging